steps:
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    apt-get clean
    apt-get update
    apt-get install -y gcc wget locales
    locale-gen en_US.UTF-8 
    wget http://sweaglesw.org/linguistics/ace/download/ace-0.9.30-x86-64.tar.gz
    tar xvzf ace-0.9.30-x86-64.tar.gz > nul
    LC_ALL=en_US.UTF-8 ./ace-0.9.30/ace -g ace/config.tdl -G jacy.dat

artifacts:
  objects:
    location: gs://my-web-apis_cloudbuild/artifacts/jacy-dat-latest
    paths: ['jacy.dat', 'ace-0.9.30-x86-64.tar.gz']  
  objects:
    location: gs://my-web-apis_cloudbuild/artifacts/jacy-dat-commit-$SHORT_SHA
    paths: ['jacy.dat', 'ace-0.9.30-x86-64.tar.gz']  
  objects:
    location: gs://my-web-apis_cloudbuild/artifacts/jacy-dat-build-$BUILD_ID
    paths: ['jacy.dat', 'ace-0.9.30-x86-64.tar.gz']  

 