steps:
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    chmod +x ./docker-build.sh
    export PROJECT_ID=$PROJECT_ID
    export BUILD_ID=$BUILD_ID
    export TAG_NAME=$TAG_NAME
    export SHORT_SHA=$SHORT_SHA
    apt-get clean
    apt-get update 
    apt-get install -y gcc wget
    wget http://sweaglesw.org/linguistics/ace/download/ace-0.9.30-x86-64.tar.gz
    tar xvzf /data/ace-0.9.30-x86-64.tar.gz > nul
    apt-get install -y locales
    locale-gen en_US.UTF-8 
    LC_ALL=en_US.UTF-8 ./ace-0.9.30/ace -g ace/config.tdl -G jacy.dat

    #./docker-build.sh jacy-dat
    #mkdir upload/
    #id=$(docker create gcr.io/$PROJECT_ID/jacy-dat)
    #docker cp $id:/data/ace-0.9.30-x86-64.tar.gz upload/latest
    #docker cp $id:/data/ace-0.9.30-x86-64.tar.gz upload/$SHORT_SHA
    #docker cp $id:/data/jacy.dat upload/latest
    #docker cp $id:/data/jacy.dat upload/$SHORT_SHA
    #docker rm -v $id

artifacts:
  objects:
    location: gs://my-web-apis_cloudbuild/artifacts/jacy-dat
    paths: ['jacy.data']  

 