# Build a baseline Ubuntu distro that supports UTF-8
FROM ubuntu:18.04 as jacy-dat
    WORKDIR /data
    RUN apt-get clean
    RUN apt-get update 
    RUN apt-get install -y gcc wget
    RUN locale-gen en_US.UTF-8 
    RUN wget http://sweaglesw.org/linguistics/ace/download/ace-0.9.30-x86-64.tar.gz
    WORKDIR /app
    RUN tar xvzf /data/ace-0.9.30-x86-64.tar.gz > nul
    RUN apt-get install -y locales
    RUN locale-gen en_US.UTF-8 
    ADD . .
    RUN LC_ALL=en_US.UTF-8 ./ace-0.9.30/ace -g ace/config.tdl -G /data/jacy.dat

